#!/usr/bin/env python

import sys
import syslog
import subprocess
import lockfile
import daemon

from time import sleep
from optparse import OptionParser



def mainloop(sensor_fname, temp_warn, temp_crit):
    """
        Actual main loop doing all the work
    """
    while True:
        # Read temperature
        f = open(sensor_fname, "r")
        temp = f.readline()
        f.close()

        temp = float(temp)
        temp /= 1000

        if temp < 10 or temp > 150:
            log(syslog.LOG_EMERG, "Read totally insante temperature: %5.1f C" % temp)
            
        if temp >= temp_warn:
            log(syslog.LOG_EMERG, "TEMPERATURE WARNING: %5.1f C" % temp)
            
        if temp >= temp_crit:
            log(syslog.LOG_EMERG, "TEMPERATURE SHUT DONW: %5.1f C" % temp)
            subprocess.Popen("shutdown -h now", shell=True)
            #subprocess.Popen("hostname", shell=True)
            
        sleep(10)
        
 

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-w", "--warn-temp", dest="temp_warn", default=80., type='float',
                  help="warning temperature (default 80 C)")
    parser.add_option("-c", "--crit-temp", dest="temp_crit", default=100., type='float',
                  help="critical temperature (default 100 C)")
    parser.add_option("-f", "--file", dest="fname", type="string",
                  default="/sys/devices/platform/i5k_amb.0/temp1_input",
                  help="File in /sys filesystem to read temperature from")
    parser.add_option("-F", "--foreground", dest="foreground", default=False, action="store_true")
    parser.add_option("-v", "--verbose", dest="verbose", default=False, action="store_true")

    (options, args) = parser.parse_args()


    syslog.openlog("heatdeath", syslog.LOG_DAEMON)
    
    def log(prio, message):
        if options.verbose:
            print message
        syslog.syslog(prio, message)
    

    # General startup logging...
    log(syslog.LOG_INFO, "Reading temperature from '%s'" % options.fname)

    if options.temp_warn > options.temp_crit:
        options.temp_warn = options.temp_crit

    log(syslog.LOG_INFO, "Warning temperature is %5.1f C" % options.temp_warn)
    log(syslog.LOG_INFO, "Critical temperature is %5.1f C" % options.temp_crit)


    #Daemonize?
    if options.foreground:
        mainloop(options.fname, options.temp_warn, options.temp_crit)
    else:
        
        with daemon.DaemonContext(
                working_directory='/tmp/',
                umask=0o002,
                pidfile=lockfile.FileLock('/var/run/heatdeath.pid') ):
            mainloop(options.fname, options.temp_warn, options.temp_crit)
 

       
