#! /bin/sh

### BEGIN INIT INFO
# Provides:          heatdeath
# Required-Start:    $remote_fs $local_fs $named $network
# Required-Stop:     $remote_fs $local_fs $named $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the slurmd
# Description:       
#                    
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DAEMON=/opt/heatdeath/heatdeath
DAEMON_OPTS=""
NAME=heatdeath
DESC="heatdeath emergency shutdown watchdog"
PIDFILE=/var/run/heatdeath.pid.lock

test -x $DAEMON || exit 0

# Include defaults if available
if [ -f /etc/default/$NAME ] ; then
	. /etc/default/$NAME
fi

# Load lsb functions
. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"
	start-stop-daemon --start --quiet --pidfile $PIDFILE \
		--exec $DAEMON -- $DAEMON_OPTS
	log_end_msg $?
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
		--exec $DAEMON
	log_end_msg $?
	;;
 reload|force-reload)
	log_daemon_msg "Reoading $DESC configuration files" "$NAME"
	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE \
		--exec $DAEMON
	log_end_msg $?
  ;;
  restart)
	log_daemon_msg "Restarting $DESC" "$NAME"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
		--exec $DAEMON
	sleep 1
	start-stop-daemon --start --quiet --pidfile $PIDFILE \
		--exec $DAEMON -- $DAEMON_OPTS
	log_end_msg $?
	;;
  *)
	N=/etc/init.d/$NAME
	log_action_msg "Usage: /etc/init.d/heatdeath {start|stop|restart|reload|force-reload}"
	exit 2
	;;
esac

exit 0
